# 服务器配置
server:
  port: 18002
  servlet:
    context-path: /

# Spring配置
spring:
  # 应用名称
  application:
    name: coder-shortlink-admin
  
  # 数据源配置
  datasource:
    # 数据库连接URL（请根据实际情况修改）
    url: jdbc:mysql://localhost:3306/shortlink?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    # 数据库用户名（请根据实际情况修改）
    username: root
    # 数据库密码（请根据实际情况修改）
    password: gzm2001..
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池类型
    type: com.zaxxer.hikari.HikariDataSource
    # HikariCP连接池配置
    hikari:
      # 连接池名称
      pool-name: HikariCP-Admin
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接池大小
      maximum-pool-size: 20
      # 连接超时时间（毫秒）
      connection-timeout: 30000
      # 空闲连接超时时间（毫秒）
      idle-timeout: 600000
      # 连接最大生命周期（毫秒）
      max-lifetime: 1800000
  
  # Redis配置
  data:
    redis:
      # Redis服务器地址（请根据实际情况修改）
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis密码（如果有的话）
      # password: 
      # 数据库索引
      database: 5
      # 连接超时时间
      timeout: 5000ms
      # Lettuce连接池配置
      lettuce:
        pool:
          # 最大连接数
          max-active: 20
          # 最大空闲连接数
          max-idle: 10
          # 最小空闲连接数
          min-idle: 5
          # 获取连接最大等待时间
          max-wait: 5000ms

# MyBatis Plus配置
mybatis-plus:
  # 实体类包路径
  type-aliases-package: org.leocoder.shortlink.admin.dao.domain
  # Mapper XML文件路径
  mapper-locations: classpath:mapper/*.xml
  # 全局配置
  global-config:
    db-config:
      # 主键类型（AUTO为自增）
      id-type: AUTO
      # 逻辑删除字段名
      logic-delete-field: delFlag
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  # 配置
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启SQL日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#配置控制台打印日志Debug
logging:
  level:
    org:
      leocoder:
        shortlink:
          admin:
            dao:
              mapper: debug